local DummyBuilderShared = {}

DummyBuilderShared.DummyLimbs = {
	"Ankle L",
	"Ankle R",

	"Arm L1",
	"Arm L2",
	"Arm L3",
	"Arm L4",
	"Arm R1",
	"Arm R2",
	"Arm R3",
	"Arm R4",

	"Cheek L",
	"Cheek R",

	"Elbow L",
	"Elbow R",

	"Fist L",
	"Fist R",

	"Foot L",
	"Foot R",

	"Head",

	"Knee L",
	"Knee R",

	"Neck",

	"Shin L1",
	"Shin L2",
	"Shin L3",
	"Shin R1",
	"Shin R2",
	"Shin R3",

	"Thigh L1",
	"Thigh L2",
	"Thigh R1",
	"Thigh R2",

	"Torso 1",
	"Torso 2",
	"Torso 3",

	"Waist 1",
	"Waist 2",

	"Wrist L",
	"Wrist R",
}

DummyBuilderShared.DummyNames = {
	"NormalDummy",
}

return DummyBuilderShared
